baseURL = 'https://MightyTAL.github.io/'
languageCode = 'en-us'
title = 'My Personal Website'
theme = 'PaperMod'

[params]
  author = "Aoling TANG"
  description = "A brief description about you."
  ShowReadingTime = true
  ShowShareButtons = true

# Social links
  github = "https://github.com/MightyAL"
  linkedin = "https://www.linkedin.com/in/yourprofile"
  twitter = "https://twitter.com/yourusername"
  email = "mailto:your.email@example.com"